language: python
python: 3.7
dist: xenial
sudo: true

services:
  - docker
  - postgresql

env:
  - DATABASE_URL=postgres://postgres@localhost/perfil

before_install:
  - cp .env.sample .env
  - pip install -r requirements.txt
  - pip install black

script:
  - pytest
  - black . --check

after_success:
  - codecov
