version: '3'
services:

  api:
    build:
      context: perfil
    depends_on:
      - db 
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./perfil:/code

  notebooks:
    build:
      context: notebooks
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/code

  db:
    image: postgres
    environment:
      - PGDATA=./perfil/db
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
