version: '3'
services:

  api:
    build:
      context: api
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./api:/code

  notebooks:
    build:
      context: notebooks
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/code

  mongo:
    image: mongo:3.6.5-jessie
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
