version: '3'
services:

  django:
    build:
      context: .
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: ["gunicorn", "perfil.wsgi:application", "--reload", "--bind", "0.0.0.0:8080", "--workers", "1", "--log-level", "INFO", "--timeout", "180"]

  redis:
    image: redis:4.0.11-alpine
